name: Build Patched AMDGPU

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:42

    steps:
      - name: Install build dependencies
        run: |
          dnf install -y dnf-plugins-core git make gcc clang elfutils-libelf-devel bc flex bison \
            rpmdevtools cpio patch kernel-devel kernel-headers

      - name: Get kernel version
        run: |
          KVER=$(rpm -q --qf "%{VERSION}-%{RELEASE}.%{ARCH}\n" kernel-devel)
          echo "KVER=$KVER" >> $GITHUB_ENV

      - name: Download kernel source
        run: |
          dnf install -y --skip-broken fedpkg
          fedpkg clone -a kernel
          cd kernel
          fedpkg sources
          tar -xf linux-*.tar.xz
          mv linux-* /usr/src/kernel-src

      - name: Download and prepare amdgpu
        run: |
          git clone --depth=1 https://github.com/RadeonOpenCompute/amdgpu-pro.git amdgpu-src
          # Remove NVIDIA firmware references to reduce size
          find amdgpu-src -type f -name '*nvidia*' -delete

      - name: Build module
        run: |
          cd amdgpu-src
          make -C /usr/src/kernels/${KVER} M=$PWD modules

      - name: Upload module
        uses: actions/upload-artifact@v4
        with:
          name: amdgpu-patched-${{ env.KVER }}
          path: amdgpu-src/*.ko
