name: Patch Fedora Kernel Source

on:
  workflow_dispatch:

jobs:
  patch-kernel:
    runs-on: ubuntu-latest
    container:
      image: fedora:42

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          dnf install -y rpm-build rpmdevtools fedpkg copr-cli

      - name: Setup RPM build tree
        run: rpmdev-setuptree

      - name: Download Fedora Kernel SRPM
        run: dnf download --source kernel

      - name: Extract the SRPM
        run: |
          rpm -ivh kernel-*.rpm

      - name: Apply Patch
        run: |
          cp ./linux-kernel-bc250.patch ~/rpmbuild/SOURCES
          sed -i '/^Patch999999: linux-kernel-test.patch$/a Patch100: linux-kernel-bc250.patch' ~/rpmbuild/SPECS/kernel.spec
          sed -i '/^ApplyOptionalPatch linux-kernel-test.patch$/a ApplyOptionalPatch linux-kernel-bc250.patch' ~/rpmbuild/SPECS/kernel.spec

      - name: Build SRPM
        run: |
          rpmbuild -bs ~/rpmbuild/SPECS/kernel.spec

      - name: Authenticate with COPR
        run: |
          mkdir -p ~/.config
          cat > ~/.config/copr <<EOF
          [copr-cli]
          login = ${{ secrets.COPR_LOGIN }}
          username = vietsman
          token = ${{ secrets.COPR_TOKEN }}
          copr_url = https://copr.fedorainfracloud.org
          EOF

      - name: Upload to COPR
        run: |
          copr-cli build vietsman/patched-kernel-bc250 ~/rpmbuild/SRPMS/kernel-*.src.rpm
