name: Build Patched AMDGPU

on:
  push:
    branches:
      - main

jobs:
  build-amdgpu:
    runs-on: ubuntu-latest
    container:
      image: fedora:42

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect latest Fedora 42 kernel (x86_64)
        id: detect
        run: |
          set -euo pipefail
          NEVRA=$(dnf repoquery --latest-limit=1 --arch=x86_64 \
            --qf '%{name}-%{version}-%{release}.%{arch}' kernel-core)
          KVER="${NEVRA#kernel-core-}"
          echo "kernel_version=${KVER}" >> $GITHUB_OUTPUT
          echo "Detected kernel: ${KVER}"

      - name: Install build dependencies
        run: |
          dnf install -y dnf-plugins-core rpm-build rpmdevtools \
            make gcc elfutils-libelf-devel kernel-devel-${{ steps.detect.outputs.kernel_version }} \
            wget cpio xz

      - name: Download Fedora kernel SRPM
        run: |
          dnf download --source kernel-core-${{ steps.detect.outputs.kernel_version }}
          rpm -ivh kernel-core-*.src.rpm

      - name: Extract AMDGPU driver only
        run: |
          mkdir -p /tmp/amdgpu-src
          SRC_DIR=$(ls -d ~/rpmbuild/SOURCES/linux-*/ | head -n1)
          cp -r $SRC_DIR/drivers/gpu/drm/amd/amdgpu /tmp/amdgpu-src/
          cp -r $SRC_DIR/drivers/gpu/drm/amd/pm/swsmu/smu11 /tmp/amdgpu-src/pm/swsmu

      - name: Apply cyan_skillfish patch
        run: |
          sed -i 's/#define[[:space:]]\+CYAN_SKILLFISH_SCLK_MIN[[:space:]]\+1000/#define CYAN_SKILLFISH_SCLK_MIN 350/' \
            /tmp/amdgpu-src/pm/swsmu/smu11/cyan_skillfish_ppt.c
          sed -i 's/#define[[:space:]]\+CYAN_SKILLFISH_SCLK_MAX[[:space:]]\+2000/#define CYAN_SKILLFISH_SCLK_MAX 2230/' \
            /tmp/amdgpu-src/pm/swsmu/smu11/cyan_skillfish_ppt.c

      - name: Build AMDGPU module
        run: |
          KVER="${{ steps.detect.outputs.kernel_version }}"
          make -C /lib/modules/$KVER/build M=/tmp/amdgpu-src modules

      - name: Upload module artifact
        uses: actions/upload-artifact@v4
        with:
          name: amdgpu-patched-${{ steps.detect.outputs.kernel_version }}
          path: /tmp/amdgpu-src/amdgpu/*.ko
