name: Build Patched AMDGPU (Fedora 42, x86_64)

on:
  workflow_dispatch:

jobs:
  build-amdgpu:
    runs-on: ubuntu-latest
    container:
      image: fedora:42
    steps:
      - name: Install build dependencies
        run: |
          dnf install -y akmods kernel-devel gcc make elfutils-libelf-devel rpm-build dnf-plugins-core

      - name: Detect latest Fedora 42 x86_64 kernel
        id: detect-kernel
        run: |
          KERNEL_PKG=$(dnf repoquery --arch=x86_64 --latest-limit=1 kernel-core)
          KERNEL_VER=$(echo $KERNEL_PKG | sed 's/kernel-core-//')
          echo "kernel_version=$KERNEL_VER" >> $GITHUB_OUTPUT

      - name: Install kernel headers for detected version
        run: |
          dnf install -y kernel-devel-${{ steps.detect-kernel.outputs.kernel_version }} \
                         kernel-headers-${{ steps.detect-kernel.outputs.kernel_version }}

      - name: Prepare akmod source dir
        run: |
          mkdir -p /usr/src/amdgpu-patched-1.0/drivers/gpu/drm/amd/pm/swsmu/smu11
          # Download Fedora kernel source matching detected version
          dnf download --source kernel
          rpm -ivh kernel-*.src.rpm
          cd /root/rpmbuild/SOURCES
          tar -xf linux-*.tar.xz
          # Copy AMDGPU driver
          cp -r linux-*/drivers/gpu/drm/amd /usr/src/amdgpu-patched-1.0/drivers/gpu/drm/
          # Apply patch to cyan_skillfish_ppt.c
          sed -i 's/#define CYAN_SKILLFISH_SCLK_MIN *1000/#define CYAN_SKILLFISH_SCLK_MIN 350/' \
              /usr/src/amdgpu-patched-1.0/drivers/gpu/drm/amd/pm/swsmu/smu11/cyan_skillfish_ppt.c
          sed -i 's/#define CYAN_SKILLFISH_SCLK_MAX *2000/#define CYAN_SKILLFISH_SCLK_MAX 2230/' \
              /usr/src/amdgpu-patched-1.0/drivers/gpu/drm/amd/pm/swsmu/smu11/cyan_skillfish_ppt.c

      - name: Create akmod spec
        run: |
          cat > /usr/src/amdgpu-patched-1.0/amdgpu-patched.spec <<'EOF'
          Name: amdgpu-patched
          Version: 1.0
          Release: 1
          Summary: Patched AMDGPU kernel module
          License: GPL
          BuildRequires: kernel-devel
          %description
          Patched AMDGPU driver with modified clock limits.
          
          %prep

          %build
          make -C /lib/modules/%{kernel_version}/build M=$PWD/drivers/gpu/drm/amd modules

          %install
          mkdir -p %{buildroot}/lib/modules/%{kernel_version}/extra
          cp drivers/gpu/drm/amd/amdgpu/amdgpu.ko %{buildroot}/lib/modules/%{kernel_version}/extra/

          %post
          /sbin/depmod -a %{kernel_version}

          %clean
          rm -rf %{buildroot}
          EOF

      - name: Build RPM
        run: |
          cd /usr/src/amdgpu-patched-1.0
          akmods --force --kernel ${{ steps.detect-kernel.outputs.kernel_version }} --akmod amdgpu-patched
          mkdir -p /artifacts
          cp /var/cache/akmods/amdgpu-patched/*.rpm /artifacts/

      - name: Upload RPM
        uses: actions/upload-artifact@v4
        with:
          name: amdgpu-patched-rpm
          path: /artifacts/*.rpm
