name: Build AMDGPU for Fedora 42

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:42
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          dnf install -y dnf-plugins-core git fedpkg rpmdevtools ncurses-devel pesign \
                         gcc bc bison flex elfutils-libelf-devel openssl-devel \
                         grubby dwarves cpio xz make

      - name: Detect latest Fedora 42 kernel (x86_64)
        id: detect
        run: |
          set -euo pipefail
          NEVRA=$(dnf repoquery --latest-limit=1 --arch=x86_64 --qf '%{name}-%{version}-%{release}.%{arch}' kernel-core)
          KVER="${NEVRA#kernel-core-}"
          echo "kernel_version=${KVER}" >> $GITHUB_OUTPUT
          echo "Detected kernel: ${KVER}"

      - name: Download kernel source
        run: |
          fedpkg clone --anonymous kernel
          cd kernel
          fedpkg sources
          tar -xf linux-*.tar.xz
          tar -xf kernel-abi-stablelists-*.tar.xz || true
          tar -xf kernel-kabi-dw-*.tar.xz || true
          mkdir -p /usr/src/kernel-src
          shopt -s dotglob
          mv linux-*/* /usr/src/kernel-src/

      - name: Apply AMDGPU patch
        run: |
          cd /usr/src/kernel-src/drivers/gpu/drm/amd/amdgpu
          # Example: patch -p1 < /path/to/your.patch
          echo "Patching AMDGPU..."
          # Place your actual patch command here

      - name: Build AMDGPU module
        run: |
          cd /usr/src/kernel-src
          make -C /lib/modules/${{ steps.detect.outputs.kernel_version }}/build M=$(pwd)/drivers/gpu/drm/amd/amdgpu modules

      - name: Upload built module
        uses: actions/upload-artifact@v4
        with:
          name: amdgpu-${{ steps.detect.outputs.kernel_version }}
          path: /usr/src/kernel-src/drivers/gpu/drm/amd/amdgpu/*.ko
